services:
  client:
    image: nginx:alpine
    ports:
      - 8090:80
    volumes:
      - ./client:/usr/share/nginx/html
    networks:
      fixed:
        ipv4_address: 172.20.0.3
  server:
    image: demo-microservice
    platform: wasi/wasm
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: mysql://root:whalehello@172.20.0.5:3306/mysql
      RUST_BACKTRACE: full
      DNS_SERVER: 127.0.0.11:53
    restart: unless-stopped
    runtime: io.containerd.wasmedge.v1
    networks:
      fixed:
        ipv4_address: 172.20.0.4
  db:
    image: mariadb:10.9
    environment:
      MYSQL_ROOT_PASSWORD: whalehello
    networks:
      fixed:
        ipv4_address: 172.20.0.5
networks:
  fixed:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
