apiVersion: v1
kind: Deployment
metadata:
  name: rust-microservice
  annotations:
    module.wasm.image/variant: compat-smart
spec:
  runtimeClassName: wasmedge-test
  containers:
  - name: rust-microservice
    image: ghcr.io/aalonsolopez/demo-microservice:latest
    ports:
    - containerPort: 8080
    env:
    - name: DATABASE_URL
      value: mysql://root:whalehello@mariadb:3306/demo
    - name: RUST_BACKTRACE
      value: full
    - name: DNS_SERVER
      value: kube-dns.kube-system.svc.cluster.local
